### PR TITLE
Add Zaamo and Zalrsc

### PR DESCRIPTION
**Pull request by ved-rivos**
Specification: https://github.com/ved-rivos/riscv-zaamo-zalrsc

### CODE REVIEW

**Comment by rpsene** [comment]
@billmcspadden-riscv this spec was also [recently ratified](https://jira.riscv.org/browse/RVS-1995). Can this be merged?

**Comment by jrtc27** [comment]
What is the official stance on A vs Za*? LLVM doesn’t believe that A implies Zalrsc or Zaamo, yet this PR says it does.

**Comment by Alasdair** [comment]
I think we merged a PR recently that moved the guards to be more in line with other files, so I think this PR needs to be rebased for that.

Other than that I don't see any issues here. Presumably at some point we will have to change the `haveZalrsc` and `haveZaamo` implementations to allow toggling them individually.

**Comment by ved-rivos** [comment]
Ideally PRs like the one the one to refactor the *aext.sail would have been done after applying the related PRs like a) for Zabha, b) Zacas, c) Zaamo, d) Zalrsc that have been queued for a while now. If these had been applied before the refactoring then the refactoring could have more comprehensively addressed these ratified extensions. I will try to get these four reworked/rebased and retested soon.

**Comment by Timmmm** [comment]
Open PRs aren't actually a queue though. This one looks very easy to rebase in any case.

**Comment by ved-rivos** [comment]
> Open PRs aren't actually a queue though. 

Open PRs are not a queue but rewriting upstream for aesthetic reasons when there are queued PRs is not kind.

**Review by Alasdair — APPROVED** [review]

**Comment by Timmmm** [comment]
> Open PRs are not a queue but rewriting upstream for aesthetic reasons when there are queued PRs is not kind.

It wasn't entirely aesthetic, and I don't think we should pause refactoring if any open PR conflicts, but in any case it wasn't my intention to be unkind or cause unnecessary rebasing (which is a right pain indeed!). Sorry about that.

I also wasn't aware of this PR tbf - would be nice if Github could highlight conflicting PRs automatically!

Anyway this LGTM and seems to be entirely uncontroversial so I'll merge it tomorrow if nobody has any objections...

**Review by Timmmm — APPROVED** [review]

**Review by arichardson — APPROVED** [review]

**Pull request merged**
