### PR TITLE
Cache c emulator

### PR DESCRIPTION
**Pull request by IDONTCRYQAQ**

### CODE REVIEW

**Comment by martinberger** [comment]
@IDONTCRYQAQ Can you provide more information what this PR does?

**Comment by IDONTCRYQAQ** [comment]
@martinberger  I'm very sorry I just learned the usage of github and accidentally clicked on the pull request, I want to delete this pull request but I don't know how to do it, I'm really sorry to affect you.

**Comment by martinberger** [comment]
@IDONTCRYQAQ Thanks, we closed the PR, so don't worry about it.

**Comment by allenjbaum** [comment]
Having said all that - at some point we will want something like this to do
proper testing of CBO ops.

**Pull request closed without merging**
