### PR TITLE
Add support for Scalar Cryptography Zbkb, Zbkc and Zbkx Extensions

### PR DESCRIPTION
**Pull request by bilalsakhawat-10xe**
This request is for Scalar Cryptography Zbkb, Zbkc and Zbkx extensions Support (https://github.com/riscv/riscv-crypto/releases/tag/v1.0.0-rc5-scalar) in the sail Model.

### CODE REVIEW

**Review by martinberger — COMMENTED** [review]
I'm surprised that there wasn't a function like `reverse_bits_in_byte` before.

**Comment by martinberger** [comment]
> I'm surprised that there wasn't a function like `reverse_bits_in_byte` before.

For some reason I cannot request a review from @allenjbaum

He was a reviewer of the original #125

**Comment by jrtc27** [comment]
> > I'm surprised that there wasn't a function like `reverse_bits_in_byte` before.
> 
> For some reason I cannot request a review from @allenjbaum
> 
> He was a reviewer of the original #125

People who aren't added as members of the repository but just accessing it via the default public permissions can't be added as reviewers by other people. If they leave a review, though, that adds themselves to the list of reviewers.

**Comment by martinberger** [comment]
> If they leave a review, though, that adds themselves to the list of reviewers.

Interesting. I had no idea. Seems like a slightly suboptimal system.

**Comment by allenjbaum** [comment]
Let me see if leaving a comment will let me become a reviewer

**Comment by jrtc27** [comment]
If you leave a "review summary" comment rather than a normal comment (i.e. go to the Files changed tab and use the green Review changes dropdown) you should get added

**Review by allenjbaum — APPROVED** [review]
I finally read the comments and followed them, and, as I recall, I intended to approve them before, so will again. I haven't review the mapping functions, just the actual op functions

**Review by jrtc27 — APPROVED** [review]
Code all looks sensible to me

**Review by martinberger — CHANGES_REQUESTED** [review]
This now has a small conflict with the merged PR 129 (for Ffh) in file model/riscv_sys_regs.sail around Line 198.

**Comment by bilalsakhawat-10xe** [comment]
> This now has a small conflict with the merged PR 129 (for Ffh) in file model/riscv_sys_regs.sail around Line 198. @bilalsakhawat-10xe

Conflict is resolved.

**Comment by jrtc27** [comment]
Rebase, don't merge, otherwise the history gets messy

**Comment by bilalsakhawat-10xe** [comment]
@jrtc27 Now I rebased and force push. And the same conflict is present. I am not sure what I did wrong. Can you please guide.

**Comment by jrtc27** [comment]
What command did you run? `git rebase origin/master` should do the right thing.

**Comment by bilalsakhawat-10xe** [comment]
Yes I ran git rebase origin/master

**Comment by jrtc27** [comment]
Well somehow you've managed to do the opposite; you've rebased master onto your branch and pushed that result, not rebase your branch on top of master, so you've got a second copy of the recent commits. I don't know how you've achieved that with that command, that doesn't make any sense, that's not how it works. Is that really the only thing you ran?

Assuming you haven't totally borked your origin/master somehow (which shouldn't be possible, it's tracks the remote ref, it's not normally mutable locally otherwise), running `git rebase origin/master` and nothing else will probably restore sanity. Failing that, `git rebase -i origin/master` and delete all the commits except your Zbk* one, as the duplicate commits might confuse it.

**Comment by bilalsakhawat-10xe** [comment]
@jrtc27 Thanks. I think I did it right this time. I'll be cautious next time.

**Review by martinberger — APPROVED** [review]

**Comment by martinberger** [comment]
Merged. Thanks @bilalsakhawat-10xe @jrtc27 @allenjbaum

**Pull request merged**
