### PR TITLE
Fix MEnvCall value

### LINKED ISSUE #294: Medeleg MEnvCall is bit 10 but it should be bit 11.
`riscv_sys_regs.sail` has this:

```
bitfield Medeleg : xlenbits = {
  SAMO_Page_Fault   : 15,
  Load_Page_Fault   : 13,
  Fetch_Page_Fault  : 12,
  MEnvCall          : 10,
  SEnvCall          : 9,
  UEnvCall          : 8,
  SAMO_Access_Fault : 7,
  SAMO_Addr_Align   : 6,
  Load_Access_Fault : 5,
  Load_Addr_Align   : 4,
  Breakpoint        : 3,
  Illegal_Instr     : 2,
  Fetch_Access_Fault: 1,
  Fetch_Addr_Align  : 0
}
```

According to the spec `MEnvCall` should be 11 not 10.

`E_M_EnvCall` is  11 in `exceptionType_to_bits()`.

### PR DESCRIPTION
**Pull request by Timmmm**
Fixes #294

### CODE REVIEW

**Comment by arichardson** [comment]
Surprised this wasn't caught by any kind of testing before

**Comment by jrtc27** [comment]
ECALLing from M-mode is a weird thing to do, and I guess TestRIG doesn’t have an ECALL template?

**Comment by billmcspadden-riscv** [comment]
I'm looking at the priv spec for medeleg,  but I am not finding a bitfield definition for the CSR.  Where are the bitfields defined?

**Comment by Timmmm** [comment]
Here:

image

**Pull request merged**
