### PR TITLE
Refactor floating point vector instructions and utilities into separate files

### PR DESCRIPTION
**Pull request by vmurali**
In addition to good software engineering practices, this also allows importing only the required files when floating point operations are not supported (for example, the file is commented out in https://github.com/microsoft/cheriot-sail/blob/main/Makefile#L49).

### CODE REVIEW

**Comment by vmurali** [comment]
Bump, any comments?

**Comment by Timmmm** [comment]
Sorry took me a while to figure out wtf the `git diff --color-moved` colours meant. How has Phabricator had moved-line detection in its UI for years but Github still hasn't??

Anyway LGTM. I'll merge in a few days if nobody else objects.

**Review by Timmmm — APPROVED** [review]

**Comment by billmcspadden-riscv** [comment]
@vmurali :   would you please resolve the conflicts.

**Comment by vmurali** [comment]
> Sorry took me a while to figure out wtf the `git diff --color-moved` colours meant. How has Phabricator had moved-line detection in its UI for years but Github still hasn't??
> 
> Anyway LGTM. I'll merge in a few days if nobody else objects.

I usually use `git diff --color-moved=dimmed-zebra` that greys out moved portions instead of giving (unhelpful) colors.


> @vmurali : would you please resolve the conflicts.
@billmcspadden-riscv I resolved the conflicts. PTAL

**Review by arichardson — APPROVED** [review]

**Comment by vmurali** [comment]
Thanks! Can someone merge it before it becomes stale again?

**Comment by Timmmm** [comment]
Yeah I'll just merge it now.

**Comment by vmurali** [comment]
Thank you!!

**Pull request merged**
