### PR TITLE
Move scattered CSRs

### PR DESCRIPTION
**Pull request by jordancarlin**
This is an initial attempt to relocate the newly scattered CSR functions and mappings.

I attempted to place everything related to a particular CSR together and in a logical place, but the compilation order of some of the files made this tricky. Especially `SAIL_SYS_SRCS` vs `SAIL_REG_SRCS`. The `sail_sys_control.sail` file could probably do with a total restructuring. 

This is structured as a series of commits that each move logically grouped CSRs to make it easier to review.

For many of the CSRs, I had to make a judgment call about what seemed to make the most sense, but there are multiple good locations for many of them and we'll probably want to move several of them around before everyone is happy with this.

### CODE REVIEW

**Comment by Timmmm** [comment]
Excellent work! I'll take a look when we've excised N.

**Comment by Timmmm** [comment]
Can you fix the conflicts (presumably due to N?) and then I'll take a look.

**Comment by jordancarlin** [comment]
> Can you fix the conflicts (presumably due to N?) and then I'll take a look.

Fixed. Was from N and the addition of menvcfgh.

**Comment by Timmmm** [comment]
This LGTM. There's definitely still organisational work to do after this (lots of files can be split up more), but we should probably defer that until after the new module system is in place.

The only change I would suggest is very minor: there are a few places where it would improve readability to add blank lines e.g. change:

```
/* machine information registers */
register mvendorid : bits(32)
register mimpid : xlenbits
register marchid : xlenbits
/* TODO: this should be readonly, and always 0 for now */
register mhartid : xlenbits
register mconfigptr : xlenbits
mapping clause csr_name_map = 0xF11  <-> "mvendorid"
mapping clause csr_name_map = 0xF12  <-> "marchid"
mapping clause csr_name_map = 0xF13  <-> "mimpid"
mapping clause csr_name_map = 0xF14  <-> "mhartid"
mapping clause csr_name_map = 0xF15  <-> "mconfigptr"
function clause is_CSR_defined(0xf11) = true // mvendorid
function clause is_CSR_defined(0xf12) = true // marchdid
function clause is_CSR_defined(0xf13) = true // mimpid
function clause is_CSR_defined(0xf14) = true // mhartid
function clause is_CSR_defined(0xf15) = true // mconfigptr
function clause read_CSR(0xF11) = zero_extend(mvendorid)
function clause read_CSR(0xF12) = marchid
function clause read_CSR(0xF13) = mimpid
function clause read_CSR(0xF14) = mhartid
function clause read_CSR(0xF15) = mconfigptr
```

to

```
/* machine information registers */
register mvendorid : bits(32)
register mimpid : xlenbits
register marchid : xlenbits
/* TODO: this should be readonly, and always 0 for now */
register mhartid : xlenbits
register mconfigptr : xlenbits

mapping clause csr_name_map = 0xF11  <-> "mvendorid"
mapping clause csr_name_map = 0xF12  <-> "marchid"
mapping clause csr_name_map = 0xF13  <-> "mimpid"
mapping clause csr_name_map = 0xF14  <-> "mhartid"
mapping clause csr_name_map = 0xF15  <-> "mconfigptr"

function clause is_CSR_defined(0xf11) = true // mvendorid
function clause is_CSR_defined(0xf12) = true // marchdid
function clause is_CSR_defined(0xf13) = true // mimpid
function clause is_CSR_defined(0xf14) = true // mhartid
function clause is_CSR_defined(0xf15) = true // mconfigptr

function clause read_CSR(0xF11) = zero_extend(mvendorid)
function clause read_CSR(0xF12) = marchid
function clause read_CSR(0xF13) = mimpid
function clause read_CSR(0xF14) = mhartid
function clause read_CSR(0xF15) = mconfigptr
```

**Review by arichardson — APPROVED** [review]

**Comment by jordancarlin** [comment]
> The only change I would suggest is very minor: there are a few places where it would improve readability to add blank lines e.g. change:

Whitespace updated

**Review by Timmmm — APPROVED** [review]

**Comment by Timmmm** [comment]
LGTM; can't see any reason not to merge this - I'll do it in a few days.

**Review by arichardson — APPROVED** [review]

**Comment by Timmmm** [comment]
I had a look through `git diff --color-moved master` and it all looks good to me.

**Comment by Timmmm** [comment]
Merged without squashing since the commits are so neat. It will probably help `git blame` keep track of things too.

**Pull request merged**
