### PR TITLE
Sail support for RVV

### PR DESCRIPTION
**Pull request by b224hisl**
We are from RIOS lab, being responsible for providing sail support for RVV(RISCV-VECTOR). 
This version of Sail-RVV codes have passed our hand-written assembly tests for LMUL=1, XLEN=64, VLEN=128 and VSEW=32. We will keep maintain this project and while generating more tests with other configs

### CODE REVIEW

**Comment by allenjbaum** [comment]
Looking quickly through this pull: you're deleting support that has already
been added , and removing the contributions, copyright and licensing from
nearly every file.
Am I misunderstanding this? It looks like you are touch files that you
shouldn't be touching.

**Comment by martinberger** [comment]
> passed our hand-written assembly tests

Have you made those tests available somewhere for the reviewers to look at (and ideally run)?

**Review by scottj97 — CHANGES_REQUESTED** [review]
Hard no. Diff shows all kinds of unrelated and inappropriate changes.

**Comment by allenjbaum** [comment]
agreed. maybe pull the latests and try again?

**Comment by b224hisl** [comment]
So sorry for that, I will check it and pull again

**Comment by martinberger** [comment]
@b224hisl Could you maybe close one of the two PRs for RVV-support?

**Comment by martinberger** [comment]
@b224hisl Any updates on this PR?

**Pull request closed without merging**
