### PR TITLE
Updates for Coq theorem prover output

### PR DESCRIPTION
**Pull request by bacam**
Compatible with the current Sail release, and includes a packaging file for opam users.

### CODE REVIEW

**Comment by ptomsich** [comment]
I don't have the experience on the Coq side of things to assess.
Who would be an appropriate reviewer?

**Comment by bacam** [comment]
There's a collaborator of ours who's probably the most familiar with this stuff.  He's at a workshop this week, so I'll ask him next week.

**Comment by ptomsich** [comment]
Plan of action:
- Merge after a positive review from a subject matter expert from Brian's group.

We didn't have any stakeholders for Coq in the golden model meeting, so we will be relying on third-party feedback.

**Review by MackieLoeffel — APPROVED** [review]
I have reviewed and tested the Coq code and can confirm that these changes work as expected. In fact, in the Islaris project (https://github.com/rems-project/islaris), we already use the changes from this branch as they are necessary to make the RISC-V Coq definitions compatible with recent versions of Coq.

**Pull request merged**
