### PR TITLE
Improved code-style and contribution documentation

### PR DESCRIPTION
**Pull request by martinberger**
Added notes about copyright headers in code, and a reminder that pull-requests ideally come with an explanation how the correctness of the PR was established.

### CODE REVIEW

**Comment by abukharmeh** [comment]
Regarding the license part, I think the CI should just run make apply_header introduced in this PR pre merge:
https://github.com/riscv/sail-riscv/commit/aff2e7aed6fd946f40a223e8cc45c0db3608f9a6

**Comment by martinberger** [comment]
> Regarding the license part, I think the CI should just run make apply_header introduced in this PR pre merge: [aff2e7a](https://github.com/riscv/sail-riscv/commit/aff2e7aed6fd946f40a223e8cc45c0db3608f9a6)

Does that always give the correct header?

**Comment by abukharmeh** [comment]
It just reads LICENCE file in the repo, and apply it to all the files.

**Comment by martinberger** [comment]
> It just reads LICENCE file in the repo, and apply it to all the files.

The sentence I added is weak so compatible with auto-adding headers. Just a reminder for people.

**Comment by abukharmeh** [comment]
Sounds good to me.

**Pull request merged**
